
import Classes.DataBaseQuerys;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author david
 */
public class AdicionarDisciplinas extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdicionarDisciplinas
     */
    public AdicionarDisciplinas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nome = new javax.swing.JTextField();
        txt_diminuitivo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        txt_info = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        txt_diminuitivo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel2.setText("Diminuitivo");

        btn_add.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        btn_add.setText("Adicionar Disciplina");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        txt_info.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(518, 518, 518)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_add)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(txt_diminuitivo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_info)))
                .addContainerGap(566, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(txt_info)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_diminuitivo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1500, 869);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        AdicionarDisciplina(txt_nome.getText(), txt_diminuitivo.getText());
    }//GEN-LAST:event_btn_addActionPerformed

    
    
    public void AdicionarDisciplina(String Nome, String Diminuitivo){
        
        
        if(VerificarSeExisteDisciplina(Nome, Diminuitivo) == true){
            
            DataBaseQuerys baseDados = new DataBaseQuerys();
            Connection conn = baseDados.getDataBaseQuerys();

            try{

                PreparedStatement statement = conn.prepareStatement("INSERT INTO disciplinas (NOME_DISCIPLINA , DIMINUITIVO_DISCIPLINA) VALUES ('"+ Nome +"','"+ Diminuitivo +"');");
                int rows = statement.executeUpdate();
                
                txt_info.setText("Disciplina adicionada com sucesso!");

            }catch(SQLException ex){
                System.out.print(ex);
            }
        }
        else{
            
            txt_info.setText("Esta disciplina já existe!");
        }
        
    }
    
    
    public boolean  VerificarSeExisteDisciplina(String Nome, String Diminuitivo){
        
        
            int count = 0;
            DataBaseQuerys baseDados = new DataBaseQuerys();
            Connection conn = baseDados.getDataBaseQuerys();
            try {
                
                PreparedStatement statement = conn.prepareStatement("SELECT COUNT(d.ID_DISCIPLINA) as Count FROM disciplinas d WHERE d.NOME_DISCIPLINA = '"+ Nome +"' OR d.DIMINUITIVO_DISCIPLINA = '"+ Diminuitivo +"'");
                

                ResultSet rs = statement.executeQuery();
                while(rs.next()){
                
                    count = rs.getInt("Count");
                }
                
                
                
                
            }catch (SQLException ex) {
                
            }
            
            if(count == 0){
                    
                    return true;
                }
                else{
                    return false;
                }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_diminuitivo;
    private javax.swing.JLabel txt_info;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
