
import Classes.Curso;
import Classes.DataBaseQuerys;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author david
 */
public class adicionar_Curso extends javax.swing.JInternalFrame {

    /**
     * Creates new form adicionar_Curso
     */
    public adicionar_Curso() {
        initComponents();
        CarregarDisciplinas();
        CarregarFormacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtDimi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        box_disciplinas = new javax.swing.JComboBox<>();
        addDisciplina = new javax.swing.JButton();
        listaDisciplinas = new java.awt.List();
        txtInfo = new javax.swing.JLabel();
        boxFormacao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        addCurso = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        txtDimi.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel1.setText("Nome Curso");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel2.setText("Diminuitivo Curso");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel3.setText("Disciplinas");

        box_disciplinas.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        addDisciplina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addDisciplina.setText("Adicionar Disciplina");
        addDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDisciplinaActionPerformed(evt);
            }
        });

        listaDisciplinas.setFont(new java.awt.Font("Dialog", 0, 19)); // NOI18N

        txtInfo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        boxFormacao.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel4.setText("Formação");

        addCurso.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        addCurso.setText("Criar Curso");
        addCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(542, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(boxFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInfo)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(box_disciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listaDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtDimi, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(542, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(txtInfo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDimi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(box_disciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(addDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listaDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1500, 869);
    }// </editor-fold>//GEN-END:initComponents

    private void addDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDisciplinaActionPerformed
        // TODO add your handling code here:
        
        AdicionarDisciplina(box_disciplinas.getSelectedItem().toString());
    }//GEN-LAST:event_addDisciplinaActionPerformed

    private void addCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCursoActionPerformed
        // TODO add your handling code here:
        
        if(txtNome.getText() == "" || txtDimi.getText() == ""){
            
            return;
        }
        
        
        String Mensagem = CriarCurso(txtNome.getText(), txtDimi.getText(), boxFormacao.getSelectedItem().toString());
        
        if(Mensagem.contains("Este curso já existe!")){
            
            txtInfo.setForeground(Color.decode("#DF0101"));
        }
        else{
            txtInfo.setForeground(Color.decode("#31B404"));
        }
        
        
        txtInfo.setText(Mensagem);
    }//GEN-LAST:event_addCursoActionPerformed

    
    
    //MINAS FUNÇÕES
    
    ArrayList<String> Disciplinas = new ArrayList<String>();
    
    
    public void CarregarDisciplinas(){
        
        
        box_disciplinas.removeAllItems();
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        try {
            
            
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM disciplinas d \n" +
            "ORDER BY d.DIMINUITIVO_DISCIPLINA");;
            
            ResultSet rs = statement.executeQuery();
             
             while(rs.next()){
                 
                 
                box_disciplinas.addItem(rs.getString("DIMINUITIVO_DISCIPLINA"));
                 
             }
             
        }catch(SQLException ex){
            System.out.print(ex);
        }
    }
    
    public void CarregarFormacao(){
        
         boxFormacao.removeAllItems();
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        try {
            
            
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM formacoes f \n" +
"ORDER BY f.NOME_FORMACAO");
            
            ResultSet rs = statement.executeQuery();
             
             while(rs.next()){
                 
                 
                boxFormacao.addItem(rs.getString("NOME_FORMACAO"));
                 
             }
             
        }catch(SQLException ex){
            System.out.print(ex);
        }
    }
    
    public void AdicionarDisciplina(String Disciplina){
        
        
        if(Disciplinas.contains(Disciplina) == false){
            Disciplinas.add(Disciplina);
        }
        else{
            
            txtInfo.setText("Esta disciplina já existe no curso!");
        }
        MostrarDisciplinas();
    }

    public void MostrarDisciplinas(){
        
        
        listaDisciplinas.removeAll();
        
        for(int i = 0; i <= Disciplinas.size() - 1; i++){
            
            listaDisciplinas.add(Disciplinas.get(i));
            
        }
    }
    
    public String CriarCurso(String Nome, String Diminuitivo, String Formacao  ){
        
        Curso curso = new Curso();
        curso.CriarCurso(Nome, Diminuitivo, Formacao, Disciplinas);
        String Mensagem = curso.AdicionarBaseDados();
        
        return Mensagem;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCurso;
    private javax.swing.JButton addDisciplina;
    private javax.swing.JComboBox<String> boxFormacao;
    private javax.swing.JComboBox<String> box_disciplinas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.List listaDisciplinas;
    private javax.swing.JTextField txtDimi;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
