
import Classes.DataBaseQuerys;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author david
 */
public class MostrarProfessor extends javax.swing.JInternalFrame {

    /**
     * Creates new form MostrarProfessor
     */
    public MostrarProfessor() {
        initComponents();
        CarregarProfessoresParaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProfessores = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_nome1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_numero1 = new javax.swing.JTextField();
        txt_sexo1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_data1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_cidadao1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_emailE1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_emailP1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_tele1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_distrito1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_concelho = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_freguesia = new javax.swing.JTextField();
        txt_localidade = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_morada = new javax.swing.JTextField();
        txt_enscricao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_disciplinas_turmas = new javax.swing.JTable();
        txt_gestorcurso = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_edit = new javax.swing.JTable();
        list1 = new java.awt.List();
        box_edit_turmas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mostrar Professores");

        tabelaProfessores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelaProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nome", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProfessores.setRowHeight(30);
        tabelaProfessores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProfessoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProfessores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1455, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ver Professores", jPanel1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel9.setText("Nome");

        txt_nome1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_nome1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel10.setText("Numero");

        txt_numero1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_numero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_sexo1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_sexo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel11.setText("Sexo");

        txt_data1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_data1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel12.setText("Data Nascimento");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel13.setText("Número Cartão Cidadão");

        txt_cidadao1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_cidadao1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel14.setText("Email Aluno");

        txt_emailE1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_emailE1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel15.setText("Email Pessoal");

        txt_emailP1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_emailP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel16.setText("Telemovel");

        txt_tele1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_tele1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel17.setText("Distrito");

        txt_distrito1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_distrito1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_distrito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_distrito1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel18.setText("Concelho");

        txt_concelho.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_concelho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel19.setText("Localidade");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel20.setText("Freguesia");

        txt_freguesia.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_freguesia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_localidade.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_localidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_codigo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel21.setText("Codigo-Postal");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel22.setText("Morada");

        txt_morada.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_morada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_morada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_moradaActionPerformed(evt);
            }
        });

        txt_enscricao.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_enscricao.setToolTipText("");
        txt_enscricao.setName(""); // NOI18N

        tabela_disciplinas_turmas.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        tabela_disciplinas_turmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Turma", "Disciplina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_disciplinas_turmas.setRowHeight(30);
        jScrollPane2.setViewportView(tabela_disciplinas_turmas);

        txt_gestorcurso.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_gestorcurso.setAutoscrolls(true);

        btn_edit.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        btn_edit.setText("Editar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cidadao1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txt_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel13)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_emailE1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(txt_tele1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txt_emailP1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_enscricao)
                    .addComponent(txt_codigo)
                    .addComponent(jLabel22)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_freguesia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_distrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_concelho, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel19)
                                        .addComponent(txt_localidade, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(txt_morada)
                    .addComponent(jLabel21)
                    .addComponent(txt_gestorcurso)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_emailE1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_distrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_concelho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cidadao1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel20))
                                .addGap(9, 9, 9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_emailP1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_freguesia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_localidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel21))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tele1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_morada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_enscricao)
                        .addGap(18, 18, 18)
                        .addComponent(txt_gestorcurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver Professor", jPanel3);

        table_edit.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        table_edit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Turma", "Disciplinas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_edit.setRowHeight(30);
        jScrollPane3.setViewportView(table_edit);

        box_edit_turmas.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel1.setText("Turmas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel2.setText("Disciplinas Turma");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel3.setText("Turmas de Professor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box_edit_turmas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(343, 343, 343)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box_edit_turmas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar Professor", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setBounds(0, 0, 1500, 869);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_moradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_moradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_moradaActionPerformed

    private void txt_distrito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_distrito1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_distrito1ActionPerformed

    private void tabelaProfessoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProfessoresMouseClicked
        // TODO add your handling code here:

        BuscarProfessorSelecionado();
    }//GEN-LAST:event_tabelaProfessoresMouseClicked


    boolean jaClicou = false;
    int ultimaLinha;
    int ultimaColuna;
    
    
    public void CarregarProfessoresParaTabela(){
        
        
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        //Guardar disciplinas do curso
        try{
            
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM professor ORDER BY NOME_PROFESSOR ASC");
            
            
            ResultSet rs = statement.executeQuery();

            while(rs.next()){
            
                DefaultTableModel model = (DefaultTableModel) tabelaProfessores.getModel();
                model.addRow(new Object[]{ rs.getString("NUMERO_PROFESSOR"), rs.getString("NOME_PROFESSOR"), rs.getString("EMAIL_PROFESSOR") });
               
               
            }
            
           
        }catch(SQLException ex){
            
            System.out.print(ex + "ALGUM ERRO");
        }
    }
    
    public void BuscarProfessorSelecionado(){
        
        
        int rowIndex = tabelaProfessores.getSelectedRow();
        int columIndex = tabelaProfessores.getSelectedColumn();
        DefaultTableModel dtm = (DefaultTableModel) tabelaProfessores.getModel();
        
        if(jaClicou == false){
            ultimaLinha = rowIndex;
            ultimaColuna = columIndex;
            
            jaClicou = true;
        }
        else{
            
            if(rowIndex == ultimaLinha && columIndex == ultimaColuna){
                jaClicou = false;
                //Abrir a info dos alunos
                CarregarDadosProf(dtm.getValueAt(rowIndex, 0).toString());
                jTabbedPane1.setSelectedIndex(1);
                
            }
            else{
                ultimaLinha = rowIndex;
                ultimaColuna = columIndex;
            }
        }  
    }
    
    public void CarregarDadosProf(String NumeroProf){
        
        
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        //Guardar disciplinas do curso
        try{
            
            int id = 0;
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM professor WHERE NUMERO_PROFESSOR = '"+ NumeroProf +"'");
            
            
            ResultSet rs = statement.executeQuery();

            while(rs.next()){
            
                txt_nome1.setText(rs.getString("NOME_PROFESSOR"));
                txt_numero1.setText(rs.getString("EMAIL_PROFESSOR"));
                txt_data1.setText(rs.getString("DATA_NASCIMENTO"));
                txt_sexo1.setText(rs.getString("SEXO"));
                txt_cidadao1.setText(rs.getString("NUMERO_CIDADAO"));
                txt_emailE1.setText(rs.getString("EMAIL_PROFESSOR"));
                txt_emailP1.setText(rs.getString("EMAIL_PESSOAL"));
                txt_tele1.setText(rs.getString("TELEMOVEL"));
                txt_distrito1.setText(rs.getString("DESTRITO"));
                txt_concelho.setText(rs.getString("CONCELHO"));
                txt_freguesia.setText(rs.getString("FREGUESIA"));
                txt_localidade.setText(rs.getString("LOCALIDADE"));
                txt_codigo.setText(rs.getString("CODIGO_POSTAL"));
                txt_morada.setText(rs.getString("MORADA")); 
                id = rs.getInt("ID_PROFESSOR");
            }
            
            BuscarDiaInscricao(id);
            BuscarTurmasDisciplinas(id);
            BuscarResponsavelCurso(id);
           
        }catch(SQLException ex){
            
            System.out.print(ex + "ALGUM ERRO");
        }
    }

    public void BuscarDiaInscricao(int id){
        
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        
        try{
            
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM registo_professor r WHERE r.ID_PROFESSOR = "+ id +" AND r.ACAO_REGISTO = 0");
            ResultSet rs = statement.executeQuery();
            
            while(rs.next()){
            
               txt_enscricao.setText("Dia de esncrição foi a " + (rs.getString("DIA") + "/" + rs.getString("MES") + "/" + rs.getString("ANO")) + " as "+ rs.getString("HORA") );
               
            }
            
           
        }catch(SQLException ex){
            
            System.out.print(ex );
        }
    }
    
    public void BuscarTurmasDisciplinas(int idProf){
        
        //
        if(tabela_disciplinas_turmas.getRowCount() > 0){
            DefaultTableModel dtm = (DefaultTableModel) tabela_disciplinas_turmas.getModel();
            dtm.setNumRows(0); 
        }
        
        if(table_edit.getRowCount() > 0){
            DefaultTableModel dtm = (DefaultTableModel) table_edit.getModel();
            dtm.setNumRows(0); 
        }
        
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        try{
            
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM professordisciplina pd, turmas t, disciplinas d WHERE pd.ID_DISCIPLINA = d.ID_DISCIPLINA AND pd.ID_TURMA = t.id_turma AND pd.ID_PROFESSOR = " + idProf + "");
            ResultSet rs = statement.executeQuery();
            
            while(rs.next()){
            
               DefaultTableModel model = (DefaultTableModel) tabela_disciplinas_turmas.getModel();
                model.addRow(new Object[]{ rs.getString("NOME_TURMA"), rs.getString("NOME_DISCIPLINA")});
            
                
                DefaultTableModel model1 = (DefaultTableModel) table_edit.getModel();
                model1.addRow(new Object[]{ rs.getString("NOME_TURMA"), rs.getString("NOME_DISCIPLINA")});
               
            }
            
            
        }catch(SQLException ex){
            
            System.out.print(ex );
        }
        
    }
    
    public void BuscarResponsavelCurso(int idProf){
        
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        try{
            
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM cursoprofessor cp, cursos c WHERE c.ID_CURSO = cp.ID_CURSO and cp.ID_PROFESSOR = " + idProf + "");
            ResultSet rs = statement.executeQuery();
            
            int count = 0;
            while(rs.next()){
            
               txt_gestorcurso.setText("Responsavel do curso " + rs.getString("NOME_CURSO") + "\n");
               count++;
            }
            
        }catch(SQLException ex){
            
            System.out.print(ex );
        }
    }
    
    public void Turmas(){
        
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        try{
            
            PreparedStatement statement = conn.prepareStatement("");
            ResultSet rs = statement.executeQuery();
            
            while(rs.next()){
            
              
            }
            
        }catch(SQLException ex){
            
            System.out.print(ex );
        }
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_edit_turmas;
    private javax.swing.JButton btn_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.List list1;
    private javax.swing.JTable tabelaProfessores;
    private javax.swing.JTable tabela_disciplinas_turmas;
    private javax.swing.JTable table_edit;
    private javax.swing.JTextField txt_cidadao1;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_concelho;
    private javax.swing.JTextField txt_data1;
    private javax.swing.JTextField txt_distrito1;
    private javax.swing.JTextField txt_emailE1;
    private javax.swing.JTextField txt_emailP1;
    private javax.swing.JLabel txt_enscricao;
    private javax.swing.JTextField txt_freguesia;
    private javax.swing.JLabel txt_gestorcurso;
    private javax.swing.JTextField txt_localidade;
    private javax.swing.JTextField txt_morada;
    private javax.swing.JTextField txt_nome1;
    private javax.swing.JTextField txt_numero1;
    private javax.swing.JTextField txt_sexo1;
    private javax.swing.JTextField txt_tele1;
    // End of variables declaration//GEN-END:variables
}
