
import Classes.Aluno;
import Classes.DataBaseQuerys;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author david
 */
public class mostraralunos extends javax.swing.JInternalFrame {

    /**
     * Creates new form mostraralunos
     */
    public mostraralunos() {
        initComponents();
        
        
        /*ModoPesquisaAtiva = 1;
        btnSearchNome.setBackground(Color.decode("#686868"));*/
        SelecionarMetodoPesquisa(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        box_pesquisa = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txt_nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_sexo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cidadao = new javax.swing.JTextField();
        txt_data = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_emailE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_tele = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_emailP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_distrito = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_concelho = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_freguesia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_localidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_morada = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_curso = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_formacao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_enscricao = new javax.swing.JLabel();
        txtTurma = new javax.swing.JLabel();
        txtinfoTurma = new javax.swing.JLabel();
        botDisciplinas = new javax.swing.JComboBox<>();
        listaNotas = new java.awt.List();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mostrar Alunos");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        tabelaAlunos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nome", "Email", "Formacao", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAlunos.setColumnSelectionAllowed(true);
        tabelaAlunos.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tabelaAlunos.setRowHeight(30);
        tabelaAlunos.getTableHeader().setReorderingAllowed(false);
        tabelaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAlunos);
        tabelaAlunos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txtSearch.setText("Procurar Aluno");
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        box_pesquisa.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        box_pesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Numero", "Curso" }));
        box_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_pesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1454, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Mostrar Alunos", jPanel1);

        jPanel2.setForeground(new java.awt.Color(240, 240, 240));

        txt_nome.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel1.setText("Nome");

        txt_numero.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_numero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel2.setText("Numero");

        txt_sexo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_sexo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel3.setText("Data Nascimento");

        txt_cidadao.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_cidadao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_data.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel4.setText("Sexo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel5.setText("Número Cartão Cidadão");

        txt_emailE.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_emailE.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel6.setText("Email Aluno");

        txt_tele.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_tele.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel7.setText("Telemovel");

        txt_emailP.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_emailP.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel8.setText("Email Pessoal");

        txt_distrito.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_distrito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_distrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_distritoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel9.setText("Distrito");

        txt_concelho.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_concelho.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel10.setText("Concelho");

        txt_freguesia.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_freguesia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel11.setText("Freguesia");

        txt_localidade.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_localidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel12.setText("Localidade");

        txt_morada.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_morada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_morada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_moradaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel13.setText("Morada");

        txt_curso.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_curso.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel14.setText("Curso");

        txt_codigo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel15.setText("Codigo-Postal");

        txt_formacao.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        txt_formacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel16.setText("Formação do Curso");

        txt_enscricao.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        txtTurma.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        txtinfoTurma.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        botDisciplinas.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        botDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDisciplinasActionPerformed(evt);
            }
        });

        listaNotas.setBackground(new java.awt.Color(240, 240, 240));
        listaNotas.setFont(new java.awt.Font("Dialog", 0, 19)); // NOI18N
        listaNotas.setForeground(new java.awt.Color(51, 51, 51));
        listaNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaNotasActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel17.setText("Disciplina");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel18.setText("Notas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(98, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txt_enscricao)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_cidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)
                                    .addComponent(txt_formacao, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_emailE, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(txt_tele, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(210, 210, 210)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTurma, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtinfoTurma, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addGap(353, 353, 353))
                                                .addComponent(txt_curso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txt_emailP, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_freguesia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_distrito, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel11))
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_concelho, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10)
                                                    .addComponent(txt_localidade, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12)))
                                            .addComponent(txt_morada, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(botDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(listaNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emailE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_distrito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_concelho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emailP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_freguesia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_localidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tele, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_morada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_formacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(txt_enscricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTurma)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtinfoTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver Aluno", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Ver Alunos");

        setBounds(0, 0, 1505, 869);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        
        CarregarAlunos(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        // TODO add your handling code here:
        txtSearch.setText("");
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        // TODO add your handling code here:
        
        if(txtSearch.getText().equals(""))
            txtSearch.setText("Procurar Aluno");
    }//GEN-LAST:event_txtSearchFocusLost

    private void tabelaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAlunosMouseClicked
        // TODO add your handling code here:
        
        MostarLinhaCarregada();
    }//GEN-LAST:event_tabelaAlunosMouseClicked

    private void box_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_pesquisaActionPerformed
        // TODO add your handling code here:
        
        SelecionarMetodoPesquisa(box_pesquisa.getSelectedIndex());
    }//GEN-LAST:event_box_pesquisaActionPerformed

    private void txt_moradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_moradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_moradaActionPerformed

    private void txt_distritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_distritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_distritoActionPerformed

    private void botDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDisciplinasActionPerformed
        // TODO add your handling code here:
        
            if(botDisciplinas.getItemCount() > 0){
                String  diminutivo = botDisciplinas.getSelectedItem().toString();
                carregarNotasDeDisciplina(diminutivo);
            }
        

    }//GEN-LAST:event_botDisciplinasActionPerformed

    private void listaNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaNotasActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_listaNotasActionPerformed


    
    //MINHAS FUNÇÕES
    int ModoPesquisaAtiva;
    // Qual aluno foi escolhido para ver a informação
    boolean jaClicou = false;
    int ultimaLinha;
    int ultimaColuna;
    int idAluno = 0;
    //Ver se o modo edicao esta ativo
    void SelecionarMetodoPesquisa(int index){
        
        //0 Nome
        //1 Numero
        //2 Curso
        ModoPesquisaAtiva = index;
        txtSearch.setText("Procurar Aluno");
        CarregarAlunos("");
    }
    
    void CarregarAlunos(String pesquisaTxt){
        
 
        if(tabelaAlunos.getRowCount() > 0){
            DefaultTableModel dtm = (DefaultTableModel) tabelaAlunos.getModel();
            dtm.setNumRows(0); 
        }
        
        
        
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        try {
            
            
            PreparedStatement statement = null;
            System.out.print(ModoPesquisaAtiva);
            switch(ModoPesquisaAtiva){
                
                case 0:
                    statement = conn.prepareStatement("SELECT a.NUMERO_ALUNO, a.NOME_ALUNO, a.EMAILESCOLAR_ALUNO,f.NOME_FORMACAO, c.NOME_CURSO FROM aluno a, cursos c, formacoes f WHERE a.CURSO_ID_ALUNO = c.ID_CURSO AND f.ID_FORMACAO = c.ID_FORMACAO AND a.NOME_ALUNO LIKE '%"+ pesquisaTxt +"%' order by a.NUMERO_ALUNO ASC");
                    
                    break;
                
                case 1:
                    
                    statement = conn.prepareStatement("SELECT a.NUMERO_ALUNO, a.NOME_ALUNO, a.EMAILESCOLAR_ALUNO,f.NOME_FORMACAO, c.NOME_CURSO FROM aluno a, cursos c, formacoes f WHERE a.CURSO_ID_ALUNO = c.ID_CURSO AND f.ID_FORMACAO = c.ID_FORMACAO AND a.NUMERO_ALUNO LIKE '%"+ pesquisaTxt +"%' order by a.NUMERO_ALUNO ASC");
                    
                    break;
                
                case 2:
                    statement = conn.prepareStatement("SELECT a.NUMERO_ALUNO, a.NOME_ALUNO, a.EMAILESCOLAR_ALUNO,f.NOME_FORMACAO, c.NOME_CURSO, c.ID_CURSO FROM aluno a, cursos c, formacoes f WHERE a.CURSO_ID_ALUNO = c.ID_CURSO AND f.ID_FORMACAO = c.ID_FORMACAO AND c.NOME_CURSO LIKE '%"+ pesquisaTxt +"%' order by a.NUMERO_ALUNO ASC");
                    
                    break;
                
            }
            
            ResultSet rs = statement.executeQuery();
             
             while(rs.next()){
                 
                 
                DefaultTableModel model = (DefaultTableModel) tabelaAlunos.getModel();
                model.addRow(new Object[]{rs.getString("NUMERO_ALUNO"),rs.getString("NOME_ALUNO"),rs.getString("EMAILESCOLAR_ALUNO"),rs.getString("NOME_FORMACAO"),rs.getString("NOME_CURSO")});
               
                 
             }
             
        }catch(SQLException ex){
            System.out.print(ex);
        }
       
        
        
    }
    
    
    void MostarLinhaCarregada(){
       
        int rowIndex = tabelaAlunos.getSelectedRow();
        int columIndex = tabelaAlunos.getSelectedColumn();
        DefaultTableModel dtm = (DefaultTableModel) tabelaAlunos.getModel();
        
        if(jaClicou == false){
            ultimaLinha = rowIndex;
            ultimaColuna = columIndex;
            
            jaClicou = true;
        }
        else{
            
            if(rowIndex == ultimaLinha && columIndex == ultimaColuna){
                jaClicou = false;
                //Abrir a info dos alunos
                CarregarDadosAlunos(dtm.getValueAt(rowIndex, 0).toString());
                jTabbedPane1.setSelectedIndex(1);
                
            }
            else{
                ultimaLinha = rowIndex;
                ultimaColuna = columIndex;
            }
        }  
    }
    
    void CarregarDadosAlunos(String numero){
        
        int idCurso = 0;
        int id = 0;
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        
         try{
            
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM aluno a, cursos c, formacoes f,  turmas t WHERE a.NUMERO_ALUNO = '"+ numero +"' AND c.ID_CURSO = f.ID_FORMACAO AND a.CURSO_ID_ALUNO = c.ID_CURSO AND t.id_turma = a.id_turma" );
            ResultSet rs = statement.executeQuery();
            
            while(rs.next()){
            
                txt_nome.setText(rs.getString("NOME_ALUNO"));
                txt_numero.setText(rs.getString("NUMERO_ALUNO"));
                txt_data.setText(rs.getString("DATA_NASCIMENTO_ALUNO"));
                txt_sexo.setText(rs.getString("SEXO_ALUNO"));
                txt_cidadao.setText(rs.getString("NUMERO_CARTAO_CIDADAO"));
                txt_formacao.setText(rs.getString("NOME_FORMACAO"));
                txt_emailE.setText(rs.getString("EMAILESCOLAR_ALUNO"));
                txt_emailP.setText(rs.getString("EMAILPESSOAL__ALUNO"));
                txt_tele.setText(rs.getString("TELEMOVEL_ALUNO"));
                txt_curso.setText(rs.getString("NOME_CURSO"));
                txt_distrito.setText(rs.getString("DISTRITO_ALUNO"));
                txt_concelho.setText(rs.getString("COCELHO_ALUNO"));
                txt_freguesia.setText(rs.getString("FREGESUIA_ALUNO"));
                txt_localidade.setText(rs.getString("LOCALIDADE_ALUNO"));
                txt_codigo.setText(rs.getString("CODIGOPOSTAL_ALUNO"));
                txt_morada.setText(rs.getString("MORADA_ALUNO"));
                id = rs.getInt("ID_ALUNO");
                txtTurma.setText("Este aluno pertence a turma " + rs.getString("NOME_TURMA"));
                txtinfoTurma.setText("Esta turma esta no " + rs.getInt("Ano") + " do curso");
                idCurso = rs.getInt("ID_CURSO");
            }
            
           
        }catch(SQLException ex){
            
            System.out.print(ex);
        }
         idAluno = id;
         BuscarDiaDeEsncricaoDoAluno(id);
         CarregarDisciplinas(idCurso);
    }
    
    void BuscarDiaDeEsncricaoDoAluno(int ID){
        
        
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        
        try{
            
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM registos_alunos r WHERE r.ID_ALUNO = "+ ID +" AND r.ACAO_REGISTO = 0");
            ResultSet rs = statement.executeQuery();
            
            while(rs.next()){
            
               txt_enscricao.setText("Dia de esncrição foi a " + (rs.getString("DIA") + "/" + rs.getString("MES") + "/" + rs.getString("ANO")) + " as "+ rs.getString("HORA") );
               
            }
            
           
        }catch(SQLException ex){
            
            System.out.print(ex );
        }
        
    }
    
    void CarregarDisciplinas(int idCurso){
        
        botDisciplinas.removeAllItems();
      
        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        //Guardar disciplinas do curso
        try{
            
            PreparedStatement statement = conn.prepareStatement("SELECT d.DIMINUITIVO_DISCIPLINA, d.ID_DISCIPLINA FROM cursos c, disciplinas d, cursodisciplina cd\n" +
            "WHERE c.ID_CURSO = cd.ID_CURSO AND d.ID_DISCIPLINA = cd.ID_DISCIPLINA AND c.ID_CURSO = " + idCurso + " ORDER BY d.ID_DISCIPLINA");
            
            
            ResultSet rs = statement.executeQuery();
            botDisciplinas.removeAllItems();
            while(rs.next()){
            
                System.out.print("\nMostrar Disciplina " + rs.getString("DIMINUITIVO_DISCIPLINA"));
                botDisciplinas.addItem(rs.getString("DIMINUITIVO_DISCIPLINA"));

               
            }
            
           
        }catch(SQLException ex){
            
            System.out.print(ex + "ALGUM ERRO aqui");
        }
 
        
    }
    
    
    void carregarNotasDeDisciplina(String diminutivo){
        listaNotas.removeAll();

        DataBaseQuerys baseDados = new DataBaseQuerys();
        Connection conn = baseDados.getDataBaseQuerys();
        
        //Guardar disciplinas do curso
        try{
            
            PreparedStatement statement = conn.prepareStatement("SELECT * FROM nota n, disciplinas d, aluno a WHERE a.ID_ALUNO = n.ID_ALUNO and n.ID_DISCIPLINA = d.ID_DISCIPLINA AND d.DIMINUITIVO_DISCIPLINA = '"+ diminutivo +"' AND a.ID_ALUNO = "+ idAluno +"");
            
            
            ResultSet rs = statement.executeQuery();
            listaNotas.removeAll();
            while(rs.next()){
            
                
                
                listaNotas.add(rs.getString("VALOR_NOTA"));

               
            }
            
           
        }catch(SQLException ex){
            
            System.out.print(ex + "ALGUM ERRO");
        }
        
    }
    
    
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> botDisciplinas;
    private javax.swing.JComboBox<String> box_pesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.List list1;
    private java.awt.List listaNotas;
    private javax.swing.JTable tabelaAlunos;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtTurma;
    private javax.swing.JTextField txt_cidadao;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_concelho;
    private javax.swing.JTextField txt_curso;
    private javax.swing.JTextField txt_data;
    private javax.swing.JTextField txt_distrito;
    private javax.swing.JTextField txt_emailE;
    private javax.swing.JTextField txt_emailP;
    private javax.swing.JLabel txt_enscricao;
    private javax.swing.JTextField txt_formacao;
    private javax.swing.JTextField txt_freguesia;
    private javax.swing.JTextField txt_localidade;
    private javax.swing.JTextField txt_morada;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_sexo;
    private javax.swing.JTextField txt_tele;
    private javax.swing.JLabel txtinfoTurma;
    // End of variables declaration//GEN-END:variables
}
